# Generated by Django 2.2 on 2019-04-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campaign', models.ManyToManyField(through='server.Campaign_Game', to='server.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign_game',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Game'),
        ),
    ]
