# Generated by Django 2.2 on 2019-04-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190410_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('upload_path', models.CharField(max_length=255)),
                ('show_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='campaign_game',
            name='photo_frame_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
